/* ── Seed data ────────────────────────────────────────────────────────── */
export const DEMO_SELLER = { user_id:'u0', name:'Demo Seller', email:'demo@campus.edu', college:'IIT Campus', rating:4.8, review_count:23, picture:'' };
export const SEED_LISTINGS = [
  { id:'l1', title:'Engineering Mathematics Vol. 3', price:280, type:'sell', category:'Books', condition:'Good', location:'Hostel A', images:['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80'], views:142, created_at:Date.now()-86400000*3, owner:DEMO_SELLER, tags:['maths','engineering'], description:'Slightly used copy, all chapters intact. Notes in margins help with exam prep!' },
  { id:'l2', title:'HP Laptop 15s (i5, 8GB RAM)', price:28000, type:'sell', category:'Electronics', condition:'Like New', location:'Hostel B', images:['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80'], views:389, created_at:Date.now()-86400000*1, owner:DEMO_SELLER, tags:['laptop','hp','computer'], description:'Barely used, purchased 6 months ago. Battery backup 6+ hours. All accessories included.' },
  { id:'l3', title:'Cycle — Hero Sprint (21-Speed)', price:350, type:'rent', category:'Cycles', condition:'Good', location:'Gate 3', images:['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80'], views:87, created_at:Date.now()-86400000*5, owner:DEMO_SELLER, rental_duration:'Per month', deposit:500, tags:['cycle','commute'], description:'Perfect condition cycle available for monthly rent. Ideal for campus commute.' },
  { id:'l4', title:'Physics Irodov — Solutions', price:0, type:'donate', category:'Books', condition:'Fair', location:'Library', images:['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&q=80'], views:56, created_at:Date.now()-86400000*2, owner:DEMO_SELLER, tags:['physics','free'], description:'Giving away free. Come pick up from the main library counter.' },
  { id:'l5', title:'Wireless Noise-Cancelling Headphones', price:2500, type:'sell', category:'Electronics', condition:'Like New', location:'Hostel C', images:['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80'], views:210, created_at:Date.now()-3600000*5, owner:DEMO_SELLER, tags:['headphones','audio','sony'], description:'Sony WH-1000XM4 in excellent condition. Barely used, original box included.' },
  { id:'l6', title:'Study Table + Chair Set', price:1800, type:'sell', category:'Furniture', condition:'Good', location:'Hostel D', images:['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&q=80'], views:74, created_at:Date.now()-86400000*7, owner:DEMO_SELLER, tags:['furniture','table','chair'], description:'Sturdy wooden study table with ergonomic chair. Moving out, must sell!' },
  { id:'l7', title:'Badminton Racket Set (2 pcs)', price:600, type:'exchange', category:'Sports', condition:'Good', location:'Sports Complex', images:['https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=600&q=80'], views:33, created_at:Date.now()-86400000*4, owner:DEMO_SELLER, tags:['badminton','sports'], description:'2 Yonex rackets, looking to exchange for cricket gear or table tennis set.' },
  { id:'l8', title:'Mini Fridge (45L Haier)', price:400, type:'rent', category:'Furniture', condition:'Good', location:'Hostel E', images:['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=600&q=80'], views:156, created_at:Date.now()-86400000*2, owner:DEMO_SELLER, rental_duration:'Per semester', deposit:1000, tags:['fridge','hostel'], description:'Compact mini fridge, perfect for hostel room. Available per semester.' },
];

